apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smesh-dashboard.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "smesh-dashboard.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "smesh-dashboard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "smesh-dashboard.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "smesh-dashboard.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range .Values.ports }}
        - name: {{ .name }}
          containerPort: {{ .port }}
          protocol: TCP
        {{- end }}
        resources:
        {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        {{- toYaml .Values.volumeMounts | nindent 8 }}
      volumes:
      {{- toYaml .Values.volumes | nindent 6 }}