apiVersion: v1
kind: Service
metadata:
  name: {{ include "smesh-dashboard.fullname" . }}
  labels:
    {{- include "smesh-dashboard.labels" . | nindent 4 }}
spec:
  ports:
  {{- range .Values.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
  {{- end }}
  selector:
    {{- include "smesh-dashboard.selectorLabels" . | nindent 4 }}
